# Generated by Django 4.1.3 on 2022-12-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_alter_members_device_ip_alter_members_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_batt', models.CharField(default='0', max_length=3)),
                ('device_signal', models.IntegerField(default=0)),
                ('device_full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceFullName', to='members.members', to_field='full_name')),
                ('mem_device_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IP', to='members.members', to_field='device_ip')),
            ],
        ),
    ]
