# Generated by Django 4.1.3 on 2022-12-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='id',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='mem_device_ip',
        ),
        migrations.AddField(
            model_name='devices',
            name='device_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', primary_key=True, serialize=False),
        ),
    ]
