# Generated by Django 4.1.3 on 2023-01-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_devices_lat_remove_devices_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='devices',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
