# Generated by Django 4.1.3 on 2023-02-01 06:58

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_devices_id_alter_devices_device_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=8, max_length=8, prefix='', primary_key=True, serialize=False),
        ),
    ]
