# Generated by Django 4.1.3 on 2023-02-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_devices_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
