# Generated by Django 4.1.3 on 2023-02-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_devices_is_connected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device_ip',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
