# Generated by Django 4.1.3 on 2023-02-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_devices_device_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='device_batt',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='device_signal',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='is_connected',
        ),
    ]
