# Generated by Django 4.1.3 on 2023-02-08 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_remove_devices_device_batt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='long',
        ),
    ]
