# Generated by Django 4.1.3 on 2023-01-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_devices_id_remove_devices_mem_device_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='devices',
            name='long',
            field=models.FloatField(default=0),
        ),
    ]
