# Generated by Django 4.1.3 on 2023-01-06 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_devices_lat_devices_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='long',
        ),
    ]
