# Generated by Django 4.1.3 on 2023-01-29 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_devices_device_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='device_ip',
            field=models.URLField(primary_key=True, serialize=False, validators=[django.core.validators.URLValidator(schemes=['http', 'rtsp', 'https'])]),
        ),
    ]
