# Generated by Django 4.1.3 on 2023-02-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0008_devices_is_connected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='device_id', serialize=False, to='devices.devices')),
            ],
        ),
    ]
