# Generated by Django 4.1.3 on 2023-02-03 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_devices_is_connected'),
        ('streams', '0002_streams_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streams',
            name='device_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='device_id', serialize=False, to='devices.devices'),
        ),
    ]
