# Generated by Django 4.1.3 on 2023-02-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_streams_device_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streams',
            name='device_url',
        ),
    ]
