# Generated by Django 4.1.3 on 2023-02-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0006_streams_device_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streams',
            name='device_url',
            field=models.CharField(max_length=100),
        ),
    ]
