# Generated by Django 4.1.3 on 2023-02-03 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_devices_device_ip'),
        ('streams', '0007_alter_streams_device_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streams',
            name='device_url',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='device_url', to='devices.devices', to_field='device_ip'),
        ),
    ]
