# Generated by Django 4.1.3 on 2023-02-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0010_remove_streams_device_url_streams_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streams',
            name='status',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
