# Generated by Django 4.1.3 on 2023-02-11 06:54

from django.db import migrations, models
import streams.locations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0011_alter_streams_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='streams',
            name='lat',
            field=models.CharField(default=streams.locations.lat_value, max_length=150),
        ),
        migrations.AddField(
            model_name='streams',
            name='long',
            field=models.CharField(default=streams.locations.long_value, max_length=150),
        ),
    ]
