# Generated by Django 4.1.3 on 2023-02-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0012_streams_lat_streams_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streams',
            name='status',
            field=models.BooleanField(default='True'),
        ),
    ]
