# Generated by Django 4.1.3 on 2023-02-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0013_alter_streams_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streams',
            name='status',
            field=models.BooleanField(default='True', editable=False),
        ),
    ]
