# Generated by Django 4.1.3 on 2023-02-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0015_remove_streams_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streams',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='streams',
            name='long',
        ),
    ]
