# Generated by Django 4.1.3 on 2023-02-08 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0011_alter_streams_status'),
        ('locations', '0002_alter_locations_lat_alter_locations_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='device_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='location_id', serialize=False, to='streams.streams'),
        ),
    ]
