# Generated by Django 4.1.3 on 2022-11-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='status',
            new_name='is_connected',
        ),
    ]
