# Generated by Django 4.1.3 on 2022-12-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_members_device_ip_alter_members_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='device_ip',
        ),
    ]
