# Generated by Django 4.1.3 on 2023-02-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20230205_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
