# Generated by Django 4.1.3 on 2023-02-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_members_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='is_connected',
            field=models.CharField(default='Disconnected', max_length=20),
        ),
    ]
